package com.huang.examine.entity;

/**
 * @author DELL
 */
public class Choose{

    /**
     * 试题科目Id
     * */
    private Integer subjectId;

    public Integer getSubjectId() {
        return subjectId;
    }

    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose.responseA
     *
     * @mbggenerated
     */
    private String responsea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose.responseB
     *
     * @mbggenerated
     */
    private String responseb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose.responseC
     *
     * @mbggenerated
     */
    private String responsec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose.responseD
     *
     * @mbggenerated
     */
    private String responsed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose.response
     *
     * @mbggenerated
     */
    private String response;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column choose.question
     *
     * @mbggenerated
     */
    private String question;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose.Id
     *
     * @return the value of choose.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose.Id
     *
     * @param id the value for choose.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose.responseA
     *
     * @return the value of choose.responseA
     *
     * @mbggenerated
     */
    public String getResponsea() {
        return responsea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose.responseA
     *
     * @param responsea the value for choose.responseA
     *
     * @mbggenerated
     */
    public void setResponsea(String responsea) {
        this.responsea = responsea == null ? null : responsea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose.responseB
     *
     * @return the value of choose.responseB
     *
     * @mbggenerated
     */
    public String getResponseb() {
        return responseb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose.responseB
     *
     * @param responseb the value for choose.responseB
     *
     * @mbggenerated
     */
    public void setResponseb(String responseb) {
        this.responseb = responseb == null ? null : responseb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose.responseC
     *
     * @return the value of choose.responseC
     *
     * @mbggenerated
     */
    public String getResponsec() {
        return responsec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose.responseC
     *
     * @param responsec the value for choose.responseC
     *
     * @mbggenerated
     */
    public void setResponsec(String responsec) {
        this.responsec = responsec == null ? null : responsec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose.responseD
     *
     * @return the value of choose.responseD
     *
     * @mbggenerated
     */
    public String getResponsed() {
        return responsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose.responseD
     *
     * @param responsed the value for choose.responseD
     *
     * @mbggenerated
     */
    public void setResponsed(String responsed) {
        this.responsed = responsed == null ? null : responsed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose.response
     *
     * @return the value of choose.response
     *
     * @mbggenerated
     */
    public String getResponse() {
        return response;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose.response
     *
     * @param response the value for choose.response
     *
     * @mbggenerated
     */
    public void setResponse(String response) {
        this.response = response == null ? null : response.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column choose.question
     *
     * @return the value of choose.question
     *
     * @mbggenerated
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column choose.question
     *
     * @param question the value for choose.question
     *
     * @mbggenerated
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }
}