package com.huang.examine.entity;

public class ExamResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examresult.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examresult.studentId
     *
     * @mbggenerated
     */
    private Integer studentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examresult.examId
     *
     * @mbggenerated
     */
    private Integer examid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examresult.questionId
     *
     * @mbggenerated
     */
    private Integer questionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examresult.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examresult.response
     *
     * @mbggenerated
     */
    private String response;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examresult.result
     *
     * @mbggenerated
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examresult.istrue
     *
     * @mbggenerated
     */
    private boolean istrue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examresult.Id
     *
     * @return the value of examresult.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examresult.Id
     *
     * @param id the value for examresult.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examresult.studentId
     *
     * @return the value of examresult.studentId
     *
     * @mbggenerated
     */
    public Integer getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examresult.studentId
     *
     * @param studentid the value for examresult.studentId
     *
     * @mbggenerated
     */
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examresult.examId
     *
     * @return the value of examresult.examId
     *
     * @mbggenerated
     */
    public Integer getExamid() {
        return examid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examresult.examId
     *
     * @param examid the value for examresult.examId
     *
     * @mbggenerated
     */
    public void setExamid(Integer examid) {
        this.examid = examid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examresult.questionId
     *
     * @return the value of examresult.questionId
     *
     * @mbggenerated
     */
    public Integer getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examresult.questionId
     *
     * @param questionid the value for examresult.questionId
     *
     * @mbggenerated
     */
    public void setQuestionid(Integer questionid) {
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examresult.type
     *
     * @return the value of examresult.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examresult.type
     *
     * @param type the value for examresult.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examresult.response
     *
     * @return the value of examresult.response
     *
     * @mbggenerated
     */
    public String getResponse() {
        return response;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examresult.response
     *
     * @param response the value for examresult.response
     *
     * @mbggenerated
     */
    public void setResponse(String response) {
        this.response = response == null ? null : response.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examresult.result
     *
     * @return the value of examresult.result
     *
     * @mbggenerated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examresult.result
     *
     * @param result the value for examresult.result
     *
     * @mbggenerated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examresult.istrue
     *
     * @return the value of examresult.istrue
     *
     * @mbggenerated
     */
    public boolean getIstrue() {
        return istrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examresult.istrue
     *
     * @param istrue the value for examresult.istrue
     *
     * @mbggenerated
     */
    public void setIstrue(boolean istrue) {
        this.istrue = istrue;
    }
}