package com.huang.examine.entity;

import java.util.Date;

/**
 * @author DELL
 */
public class Exam {
    private Page page;

    public Page getPage() {
        return page;
    }

    public void setPage(Page page) {
        this.page = page;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.time
     *
     * @mbggenerated
     */
    private Integer time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.course
     *
     * @mbggenerated
     */
    private String course;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.pageId
     *
     * @mbggenerated
     */
    private Integer pageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam.number
     *
     * @mbggenerated
     */
    private String number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.Id
     *
     * @return the value of exam.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.Id
     *
     * @param id the value for exam.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.name
     *
     * @return the value of exam.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.name
     *
     * @param name the value for exam.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.time
     *
     * @return the value of exam.time
     *
     * @mbggenerated
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.time
     *
     * @param time the value for exam.time
     *
     * @mbggenerated
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.date
     *
     * @return the value of exam.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.date
     *
     * @param date the value for exam.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.course
     *
     * @return the value of exam.course
     *
     * @mbggenerated
     */
    public String getCourse() {
        return course;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.course
     *
     * @param course the value for exam.course
     *
     * @mbggenerated
     */
    public void setCourse(String course) {
        this.course = course == null ? null : course.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.pageId
     *
     * @return the value of exam.pageId
     *
     * @mbggenerated
     */
    public Integer getPageid() {
        return pageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.pageId
     *
     * @param pageid the value for exam.pageId
     *
     * @mbggenerated
     */
    public void setPageid(Integer pageid) {
        this.pageid = pageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.status
     *
     * @return the value of exam.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.status
     *
     * @param status the value for exam.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam.number
     *
     * @return the value of exam.number
     *
     * @mbggenerated
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam.number
     *
     * @param number the value for exam.number
     *
     * @mbggenerated
     */
    public void setNumber(String number) {
        this.number = number == null ? null : number.trim();
    }
}