package com.huang.examine.entity;

/**
 * @author DELL
 */
public class Judge {

    /**
     * 试题科目Id
     * */
    private Integer subjectId;

    public Integer getSubjectId() {
        return subjectId;
    }

    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judge.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judge.response
     *
     * @mbggenerated
     */
    private Boolean response;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column judge.question
     *
     * @mbggenerated
     */
    private String question;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judge.Id
     *
     * @return the value of judge.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judge.Id
     *
     * @param id the value for judge.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judge.response
     *
     * @return the value of judge.response
     *
     * @mbggenerated
     */
    public Boolean getResponse() {
        return response;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judge.response
     *
     * @param response the value for judge.response
     *
     * @mbggenerated
     */
    public void setResponse(Boolean response) {
        this.response = response;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column judge.question
     *
     * @return the value of judge.question
     *
     * @mbggenerated
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column judge.question
     *
     * @param question the value for judge.question
     *
     * @mbggenerated
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }
}