package com.huang.examine.entity;

/**
 * @author DELL
 */
public class MockResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mockresult.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mockresult.mockId
     *
     * @mbggenerated
     */
    private Integer mockid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mockresult.questionId
     *
     * @mbggenerated
     */
    private Integer questionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mockresult.response
     *
     * @mbggenerated
     */
    private String response;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mockresult.result
     *
     * @mbggenerated
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mockresult.isTrue
     *
     * @mbggenerated
     */
    private Boolean istrue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mockresult.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mockresult.Id
     *
     * @return the value of mockresult.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mockresult.Id
     *
     * @param id the value for mockresult.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mockresult.mockId
     *
     * @return the value of mockresult.mockId
     *
     * @mbggenerated
     */
    public Integer getMockid() {
        return mockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mockresult.mockId
     *
     * @param mockid the value for mockresult.mockId
     *
     * @mbggenerated
     */
    public void setMockid(Integer mockid) {
        this.mockid = mockid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mockresult.questionId
     *
     * @return the value of mockresult.questionId
     *
     * @mbggenerated
     */
    public Integer getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mockresult.questionId
     *
     * @param questionid the value for mockresult.questionId
     *
     * @mbggenerated
     */
    public void setQuestionid(Integer questionid) {
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mockresult.response
     *
     * @return the value of mockresult.response
     *
     * @mbggenerated
     */
    public String getResponse() {
        return response;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mockresult.response
     *
     * @param response the value for mockresult.response
     *
     * @mbggenerated
     */
    public void setResponse(String response) {
        this.response = response == null ? null : response.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mockresult.result
     *
     * @return the value of mockresult.result
     *
     * @mbggenerated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mockresult.result
     *
     * @param result the value for mockresult.result
     *
     * @mbggenerated
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mockresult.isTrue
     *
     * @return the value of mockresult.isTrue
     *
     * @mbggenerated
     */
    public Boolean getIstrue() {
        return istrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mockresult.isTrue
     *
     * @param istrue the value for mockresult.isTrue
     *
     * @mbggenerated
     */
    public void setIstrue(Boolean istrue) {
        this.istrue = istrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mockresult.type
     *
     * @return the value of mockresult.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mockresult.type
     *
     * @param type the value for mockresult.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }
}