package com.huang.examine.entity;

public class PageQues {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageques.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageques.pageId
     *
     * @mbggenerated
     */
    private Integer pageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageques.questionId
     *
     * @mbggenerated
     */
    private Integer questionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pageques.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageques.Id
     *
     * @return the value of pageques.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageques.Id
     *
     * @param id the value for pageques.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageques.pageId
     *
     * @return the value of pageques.pageId
     *
     * @mbggenerated
     */
    public Integer getPageid() {
        return pageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageques.pageId
     *
     * @param pageid the value for pageques.pageId
     *
     * @mbggenerated
     */
    public void setPageid(Integer pageid) {
        this.pageid = pageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageques.questionId
     *
     * @return the value of pageques.questionId
     *
     * @mbggenerated
     */
    public Integer getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageques.questionId
     *
     * @param questionid the value for pageques.questionId
     *
     * @mbggenerated
     */
    public void setQuestionid(Integer questionid) {
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pageques.type
     *
     * @return the value of pageques.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pageques.type
     *
     * @param type the value for pageques.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }
}