package com.huang.examine.entity;

public class Subject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.collogeName
     *
     * @mbggenerated
     */
    private String collogename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subject.majorName
     *
     * @mbggenerated
     */
    private String majorname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.Id
     *
     * @return the value of subject.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.Id
     *
     * @param id the value for subject.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.name
     *
     * @return the value of subject.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.name
     *
     * @param name the value for subject.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.collogeName
     *
     * @return the value of subject.collogeName
     *
     * @mbggenerated
     */
    public String getCollogename() {
        return collogename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.collogeName
     *
     * @param collogename the value for subject.collogeName
     *
     * @mbggenerated
     */
    public void setCollogename(String collogename) {
        this.collogename = collogename == null ? null : collogename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subject.majorName
     *
     * @return the value of subject.majorName
     *
     * @mbggenerated
     */
    public String getMajorname() {
        return majorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subject.majorName
     *
     * @param majorname the value for subject.majorName
     *
     * @mbggenerated
     */
    public void setMajorname(String majorname) {
        this.majorname = majorname == null ? null : majorname.trim();
    }
}