package com.huang.examine.entity;

public class UserExam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userexam.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userexam.user
     *
     * @mbggenerated
     */
    private Integer user;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userexam.exam
     *
     * @mbggenerated
     */
    private Integer exam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userexam.usertype
     *
     * @mbggenerated
     */
    private Byte usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userexam.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userexam.Id
     *
     * @return the value of userexam.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userexam.Id
     *
     * @param id the value for userexam.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userexam.user
     *
     * @return the value of userexam.user
     *
     * @mbggenerated
     */
    public Integer getuser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userexam.user
     *
     * @param user the value for userexam.user
     *
     * @mbggenerated
     */
    public void setuser(Integer user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userexam.exam
     *
     * @return the value of userexam.exam
     *
     * @mbggenerated
     */
    public Integer getexam() {
        return exam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userexam.exam
     *
     * @param exam the value for userexam.exam
     *
     * @mbggenerated
     */
    public void setexam(Integer exam) {
        this.exam = exam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userexam.usertype
     *
     * @return the value of userexam.usertype
     *
     * @mbggenerated
     */
    public Byte getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userexam.usertype
     *
     * @param usertype the value for userexam.usertype
     *
     * @mbggenerated
     */
    public void setUsertype(Byte usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userexam.score
     *
     * @return the value of userexam.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userexam.score
     *
     * @param score the value for userexam.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}