package com.huang.examine.entity;

public class UserExam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userexam.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userexam.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userexam.examId
     *
     * @mbggenerated
     */
    private Integer examid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userexam.usertype
     *
     * @mbggenerated
     */
    private Byte usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userexam.score
     *
     * @mbggenerated
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userexam.Id
     *
     * @return the value of userexam.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userexam.Id
     *
     * @param id the value for userexam.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userexam.userId
     *
     * @return the value of userexam.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userexam.userId
     *
     * @param userid the value for userexam.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userexam.examId
     *
     * @return the value of userexam.examId
     *
     * @mbggenerated
     */
    public Integer getExamid() {
        return examid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userexam.examId
     *
     * @param examid the value for userexam.examId
     *
     * @mbggenerated
     */
    public void setExamid(Integer examid) {
        this.examid = examid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userexam.usertype
     *
     * @return the value of userexam.usertype
     *
     * @mbggenerated
     */
    public Byte getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userexam.usertype
     *
     * @param usertype the value for userexam.usertype
     *
     * @mbggenerated
     */
    public void setUsertype(Byte usertype) {
        this.usertype = usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userexam.score
     *
     * @return the value of userexam.score
     *
     * @mbggenerated
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userexam.score
     *
     * @param score the value for userexam.score
     *
     * @mbggenerated
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}