package com.huang.examine.mapper;

import com.huang.examine.entity.Choose;

public interface ChooseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose
     *
     * @mbggenerated
     */
    int insert(Choose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose
     *
     * @mbggenerated
     */
    int insertSelective(Choose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose
     *
     * @mbggenerated
     */
    Choose selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Choose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Choose record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table choose
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Choose record);
}