package com.huang.examine.mapper;

import com.huang.examine.entity.ExamResult;

public interface ExamResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examresult
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examresult
     *
     * @mbggenerated
     */
    int insert(ExamResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examresult
     *
     * @mbggenerated
     */
    int insertSelective(ExamResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examresult
     *
     * @mbggenerated
     */
    ExamResult selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examresult
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExamResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table examresult
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExamResult record);
}