package com.huang.examine.mapper;

import com.huang.examine.entity.Judge;

public interface JudgeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judge
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judge
     *
     * @mbggenerated
     */
    int insert(Judge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judge
     *
     * @mbggenerated
     */
    int insertSelective(Judge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judge
     *
     * @mbggenerated
     */
    Judge selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judge
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Judge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judge
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Judge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table judge
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Judge record);
}