package com.huang.examine.mapper;

import com.huang.examine.entity.MockResult;

public interface MockResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mockresult
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mockresult
     *
     * @mbggenerated
     */
    int insert(MockResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mockresult
     *
     * @mbggenerated
     */
    int insertSelective(MockResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mockresult
     *
     * @mbggenerated
     */
    MockResult selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mockresult
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MockResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mockresult
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MockResult record);
}