package com.huang.examine.mapper;

import com.huang.examine.entity.MockExam;

public interface MockExamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mockexam
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mockexam
     *
     * @mbggenerated
     */
    int insert(MockExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mockexam
     *
     * @mbggenerated
     */
    int insertSelective(MockExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mockexam
     *
     * @mbggenerated
     */
    MockExam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mockexam
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MockExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mockexam
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MockExam record);
}