package com.huang.examine.mapper;

import com.huang.examine.entity.PageDetail;

public interface PageDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagedetail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagedetail
     *
     * @mbggenerated
     */
    int insert(PageDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagedetail
     *
     * @mbggenerated
     */
    int insertSelective(PageDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagedetail
     *
     * @mbggenerated
     */
    PageDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagedetail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PageDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagedetail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PageDetail record);
}