package com.huang.examine.mapper;

import com.huang.examine.entity.Page;

public interface PageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbggenerated
     */
    int insert(Page record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbggenerated
     */
    int insertSelective(Page record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbggenerated
     */
    Page selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Page record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Page record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Page record);
}