package com.huang.examine.mapper;

import com.huang.examine.entity.PageQues;

public interface PageQuesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageques
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageques
     *
     * @mbggenerated
     */
    int insert(PageQues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageques
     *
     * @mbggenerated
     */
    int insertSelective(PageQues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageques
     *
     * @mbggenerated
     */
    PageQues selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageques
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PageQues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pageques
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PageQues record);
}