package com.huang.examine.mapper;

import com.huang.examine.entity.Specialty;

public interface SpecialtyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specialty
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specialty
     *
     * @mbggenerated
     */
    int insert(Specialty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specialty
     *
     * @mbggenerated
     */
    int insertSelective(Specialty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specialty
     *
     * @mbggenerated
     */
    Specialty selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specialty
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Specialty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table specialty
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Specialty record);
}