package com.huang.examine.mapper;

import com.huang.examine.entity.UserExam;

public interface UserExamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userexam
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userexam
     *
     * @mbggenerated
     */
    int insert(UserExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userexam
     *
     * @mbggenerated
     */
    int insertSelective(UserExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userexam
     *
     * @mbggenerated
     */
    UserExam selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userexam
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserExam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userexam
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserExam record);
}